### ISSUE TITLE
Unable to build source after cloning. Help needed to set up the source 

### ISSUE THREAD

**Issue by sujanrao17** [DevLight-Mobile-Agency/NavigationTabBar#10]
Error:A problem occurred configuring root project 'NavigationTabBar'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.github.dcendents:android-maven-gradle-plugin:1.3.
     Required by:
         :NavigationTabBar:unspecified
      > Could not resolve com.github.dcendents:android-maven-gradle-plugin:1.3.
         > Could not get resource 'https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.pom'.
               > Connection to http://127.0.0.1:8888 refused
   > Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:1.1.
     Required by:
         :NavigationTabBar:unspecified
      > Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:1.1.
         > Could not get resource 'https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.1/gradle-bintray-plugin-1.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.1/gradle-bintray-plugin-1.1.pom'.
               > Connection to http://127.0.0.1:8888 refused

**Comment by GIGAMOLE** [comment]
What exactly u cant build. Source, sample app or gradle compile? Thanks.

**Comment by sujanrao17** [comment]
Its with gradle. I have problem with class path of main gradle. Gradle throws connection refused

**Comment by GIGAMOLE** [comment]
What version? Latest?

**Comment by GIGAMOLE** [comment]
I dont know what is happen, but my 1.1.5 version is stable and compile in my projects. Try to clean project, cache of your AndroidStudio or something.

**Comment by sujanrao17** [comment]
it seemed to be some problem with classpath, its resolved now. Thanks anyways
