### ISSUE TITLE
How can i modify the size of title or the size of pic?

### ISSUE THREAD

**Issue by AlphaHans** [DevLight-Mobile-Agency/NavigationTabBar#12]
![image](https://cloud.githubusercontent.com/assets/16743494/14911482/38ef1edc-0e28-11e6-9d66-f0c26792b0e5.png)
like this error! so,How can i modify the size of title or the size of pic?

**Comment by GIGAMOLE** [comment]
Hello. Thanks for your response. Try to wrap your NTB in FrameLayout. Its almost the same issue:
https://github.com/DevLight-Mobile-Agency/NavigationTabBar/issues/6

**Comment by AlphaHans** [comment]
@GIGAMOLE  I'm sorry。Is it my misunderstanding？ I just totally copy your layout code from the samples. The layout's name is "acitivty_horizontal_ntb".
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#423752"
    android:orientation="vertical">

    <android.support.v4.view.ViewPager
        android:id="@+id/home_view_pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/wrapper_ntb_horizontal"/>

    <FrameLayout
        android:id="@+id/wrapper_ntb_horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true">

        <View
            android:id="@+id/bg_ntb_horizontal"
            android:layout_width="match_parent"
            android:layout_height="52dp"
            android:layout_gravity="bottom"
            android:background="#605271"/>

        <com.gigamole.library.NavigationTabBar
            android:id="@+id/home_bottom_tab"
            android:layout_width="match_parent"
            android:layout_height="60dp"
            app:ntb_badge_gravity="top"
            app:ntb_badge_position="right"
            app:ntb_badged="true"
            app:ntb_scaled="true"
            app:ntb_title_mode="all"
            app:ntb_titled="true"/>

    </FrameLayout>

</RelativeLayout>
```
I just change the ViewPager's id and NTB's id. but it seems that it doesn't work!

![image](https://cloud.githubusercontent.com/assets/16743494/14918582/4a9b4dac-0e57-11e6-85f4-ff153308d773.png)
Would you help me debug again?

**Comment by AlphaHans** [comment]
@GIGAMOLE OMG！ I just download your samples,and copy your activity and layout into my project,and i find that it doesn't work ,too!  Why? Do you have and idea?

**Comment by AlphaHans** [comment]
@GIGAMOLE  Hello! I had written down a letter to your gmail!  I'm waiting for your response! please help me! Thanks!

**Comment by GIGAMOLE** [comment]
I dont understand why its happen. I have test on meny devices, but this bug i have not seen before. What is yor device? Is this tablet? Maybe your icons incorrect?

**Comment by AlphaHans** [comment]
@GIGAMOLE  I think it's not about devices. When I run your samples ,it's working! But in my project, it doesn't work!  My letter is not sent successfully, i try send again. In the letter, my project is included

**Comment by AlphaHans** [comment]
@GIGAMOLE  can you offer me your outlook 's email? because in china,it is diffcult to send email to gmail.    lol

**Comment by AlphaHans** [comment]
@GIGAMOLE aaaaaa~~~~ I find the problem!!!!  
 the icon need to put into the drawable folder!
![image](https://cloud.githubusercontent.com/assets/16743494/14922565/dd0bd676-0e6a-11e6-89bf-015a7329d66f.png)
![image](https://cloud.githubusercontent.com/assets/16743494/14922638/527dd4cc-0e6b-11e6-85a0-d3207d864eb5.png)
But at first , i brought them into the drawable-xxdpi folder.!
![image](https://cloud.githubusercontent.com/assets/16743494/14922609/224b07de-0e6b-11e6-9d3f-4b57f755156b.png)
![image](https://cloud.githubusercontent.com/assets/16743494/14922627/428354a2-0e6b-11e6-8285-ae50759bb004.png)

aaaa~~Thanks for your patience !!! Thanks for your answer!!!

**Comment by GIGAMOLE** [comment]
Thank you for this issue. Its great that you fix your problem. Also, i have some tips. If you put your drawable into speciffic folder you must put in all other folders according to the screen specs, if not just put your drawables into drawable folder, like in your situation. Thanks.

**Comment by whdals0** [comment]
> @GIGAMOLE aaaaaa~~~~ I find the problem!!!!
> the icon need to put into the drawable folder!
> ![image](https://cloud.githubusercontent.com/assets/16743494/14922565/dd0bd676-0e6a-11e6-89bf-015a7329d66f.png)
> ![image](https://cloud.githubusercontent.com/assets/16743494/14922638/527dd4cc-0e6b-11e6-85a0-d3207d864eb5.png)
> But at first , i brought them into the drawable-xxdpi folder.!
> ![image](https://cloud.githubusercontent.com/assets/16743494/14922609/224b07de-0e6b-11e6-9d3f-4b57f755156b.png)
> ![image](https://cloud.githubusercontent.com/assets/16743494/14922627/428354a2-0e6b-11e6-8285-ae50759bb004.png)
> 
> aaaa~~Thanks for your patience !!! Thanks for your answer!!!

Thank you so much. GIGAMOLE. It's perfect solution!!!!

**Comment by whdals0** [comment]
Thank you so much. GIGAMOLE. It's perfect solution!!!!
