### ISSUE TITLE
Oddities in sample app

### ISSUE THREAD

**Issue by MarcinOrlowski** [DevLight-Mobile-Agency/NavigationTabBar#14]
Hi,

I noticed your demo app does something that I'd not really expect:

```
    @Override
    protected void onDestroy() {
        super.onDestroy();
        System.runFinalization();
        Runtime.getRuntime().gc();
        System.gc();
    }

```

Is there any reason for forcing this in your app?

**Comment by GIGAMOLE** [comment]
Hello. Its just for sample. Id made it for testing. Iam load an icons in very big resolution, all of them stay in memory so iam clear memory. Forget to clear it. Wait for update. Thanks.
