### ISSUE TITLE
how can I change the color of the badges?

### ISSUE THREAD

**Issue by jgamedev** [DevLight-Mobile-Agency/NavigationTabBar#15]
Could not find this customization option.

Obviously white colored badges can only make sense on dark themed apps like the example that you created, so that limitation makes the badge feature useless for a lot of people.

I think if implementing a custom color is dificult you could at least make an option for red badges, which are the default for most apps

**Comment by GIGAMOLE** [comment]
Hello. Thanks for an idea. Wait for improvments. Thanks.

**Comment by GIGAMOLE** [comment]
Hello. Thanks for an idea. Wait for improvments. Thanks.

**Comment by GIGAMOLE** [comment]
Hello. U can update NTB to 1.1.6 where you can set custom colors to badge. Thanks for enhancement.

**Comment by jgamedev** [comment]
Whoa, that was fast! Thank you so much, I hope to be able to test it on Monday when I'm back at the office.
