### ISSUE TITLE
Support for scrolling

### ISSUE THREAD

**Issue by sandeshlasnapure** [DevLight-Mobile-Agency/NavigationTabBar#16]
How can I attach navigation bar to coordinator layout?

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue. What exactly do you need in CoordinatorLayout?

**Comment by sandeshlasnapure** [comment]
Should work like FAB button.
Show hide bottom bar on scroll and should be compatible to handle  CoordinatorLayout features.

**Comment by GIGAMOLE** [comment]
Ok. I am trying to handle this.

**Comment by sandeshlasnapure** [comment]
thanks

**Comment by GIGAMOLE** [comment]
Hello. Check out sample how to achive your effect. Just wrap NTB into AppBarLayout and create what you want.
