### ISSUE TITLE
Orientation change 

### ISSUE THREAD

**Issue by sandeshlasnapure** [DevLight-Mobile-Agency/NavigationTabBar#17]
While using demo app I have encountered this issue on orientaion change.
![screenshot_2016-05-09-08-08-26](https://cloud.githubusercontent.com/assets/12455411/15107869/29f73e3a-15f0-11e6-85a4-dc12ce2d2834.png)
![screenshot_2016-05-09-08-08-29](https://cloud.githubusercontent.com/assets/12455411/15107868/29f40800-15f0-11e6-8113-d81499438592.png)

**Comment by GIGAMOLE** [comment]
Hello. I am trying to fix this.

**Comment by GIGAMOLE** [comment]
What phone model for this bug.

**Comment by sandeshlasnapure** [comment]
Samsung galaxy S4 os Lollypop 5.0

**Comment by GIGAMOLE** [comment]
Its the same issue as was in https://github.com/DevLight-Mobile-Agency/NavigationTabBar/issues/8.
