### ISSUE TITLE
 can't find the library

### ISSUE THREAD

**Issue by hmxlkexl000** [DevLight-Mobile-Agency/NavigationTabBar#19]
i like your libraries , but i can't find the library from dependencies in android studio ,so i can't use it ,is anything wrong?

**Comment by GIGAMOLE** [comment]
Hello. Thanks for feedback.

Or use Gradle jCenter:

dependencies {
    repositories {
        mavenCentral()
        maven {
            url  'http://dl.bintray.com/gigamole/maven/'
        }
    }
    compile 'com.github.devlight.navigationtabbar:library:+'
}
Or Gradle Maven Central:

compile 'com.github.devlight.navigationtabbar:library:1.1.6'
Or Maven:

<dependency>
    <groupId>com.github.devlight.navigationtabbar</groupId>
    <artifactId>library</artifactId>
    <version>1.1.6</version>
    <type>aar</type>
</dependency>
