### ISSUE TITLE
Disable index selection

### ISSUE THREAD

**Issue by aathirasanthosh** [DevLight-Mobile-Agency/NavigationTabBar#2]
when i open the activity model index will be active. for an example if i set   models5.setModelIndex(1,true); the first will be active. i need to disable this. when i open the activity all index should be disable and if i select one need to active that select one.is it possible?

**Comment by GIGAMOLE** [comment]
This feature only available in non ViewPager mode. As I understand, you need to have a NTB with no selection and when click on some model the NTB provide selection and continue own work?

**Comment by aathirasanthosh** [comment]
yes you are right. it is a non view pager and  I need NTB with no selection

**Comment by GIGAMOLE** [comment]
Ok. Wait for this improvment. Thanks.

**Comment by GIGAMOLE** [comment]
Check nwe release 1.1.1. Thanks.
