### ISSUE TITLE
How to keep tab icon as original

### ISSUE THREAD

**Issue by shashank090789** [DevLight-Mobile-Agency/NavigationTabBar#20]
I want to keep the icon of the tab as original .

**Comment by GIGAMOLE** [comment]
Hello. What do you meen?

**Comment by shashank090789** [comment]
The icon in the tab is not appearing as original one , in the place of the icon there is a round white circle
appears. I want the same icon as original which I put in the drawable folder

**Comment by GIGAMOLE** [comment]
Ok. Wait for new release.

**Comment by GIGAMOLE** [comment]
Hello. Update 1.2.0 is on the rails. You can set tint mode tou your NTB.
