### ISSUE TITLE
get position without using view pager

### ISSUE THREAD

**Issue by tux-world** [DevLight-Mobile-Agency/NavigationTabBar#31]
Hi. in this library how can i found whats position of tab without using viewpager? i dont like to use view pager and i want to know current position when user scrolling

**Comment by GIGAMOLE** [comment]
Hello. Thanks for question. Just use method getModelIndex().

**Comment by tux-world** [comment]
@GIGAMOLE Thanks man. please let me to test that

**Comment by tux-world** [comment]
@GIGAMOLE how can i get that after click on items?

this code is not correct

```
        navigationTabBar.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                navigationTabBar.getModelIndex();
            }
        });
```

**Comment by GIGAMOLE** [comment]
Use the onTabIndexSelectListener in method onStartSelect which trigger when you tab on selected model.

**Comment by tux-world** [comment]
Thanks, and how can i set default tab for that? when i dont use viewPager, navigation tab dont have default active tab, it means i dont have any circle on navigation to see that for users

**Comment by tux-world** [comment]
I'm sorry i found it, excuse me sir
