### ISSUE TITLE
Set some tab with title and other not

### ISSUE THREAD

**Issue by darcheville06** [DevLight-Mobile-Agency/NavigationTabBar#34]
Hello,

is it possible to have tab elements with title and other with no title in same tab bar ?

Thanks and Regards

**Comment by darcheville06** [comment]
When i do that : 
                    add(new NavigationTabBar.Model.Builder(
                            getResources().getDrawable(R.drawable.tab_bar_icone_missions),
                            Color.parseColor("#000000")
                    ).title(getString(R.string.tab_bar_missions))
                            .build());

                    add(new NavigationTabBar.Model.Builder(
                            getResources().getDrawable(R.drawable.icone_push_tab),
                            Color.parseColor("#000000")
                    ).title("").build());

i have no title on the second tab but the icon is small

**Comment by GIGAMOLE** [comment]
Hello. Thanks for help wanted. What title mode do you use? I have tried it many times and there no small icons.

**Comment by darcheville06** [comment]
Thanks for your help. I am using : 
    <com.gigamole.navigationtabbar.ntb.NavigationTabBar
        android:id="@+id/navigationTabBar"
        android:layout_width="match_parent"
        android:layout_height="90dp"
        app:ntb_badge_gravity="top"
        app:ntb_badge_position="right"
        app:ntb_badged="false"
        app:ntb_scaled="true"
        app:ntb_tinted="true"
        app:ntb_title_mode="all"
        app:ntb_titled="true"
        app:ntb_swiped="true"/>

**Comment by darcheville06** [comment]
I have small icons with no title when im using 
          add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.icone_push_tab),
                        Color.parseColor("#000000")
                ).title("").build());

**Comment by GIGAMOLE** [comment]
Can you provide any screenshots?

**Comment by GIGAMOLE** [comment]
Try to set space symbol on tab symbol in title, nor "".

**Comment by darcheville06** [comment]
![tab_bar1](https://cloud.githubusercontent.com/assets/17909686/16586255/314ce0f2-42c5-11e6-9edb-2566c33c5009.png)

**Comment by darcheville06** [comment]
(the selected tab) ok i will try

**Comment by darcheville06** [comment]
it does not work :/

**Comment by darcheville06** [comment]
i put a space symbol in title(" ") but it does the same

**Comment by GIGAMOLE** [comment]
Ohhh. You about that. There no feature to do the icon at the center, cause all icons must be in all level. Thanks.
