### ISSUE TITLE
button borders

### ISSUE THREAD

**Issue by xm-repo** [DevLight-Mobile-Agency/NavigationTabBar#36]
i think it would be good to have some options for tabbar buttons borders (such as colors, width, smh else maybe)

**Comment by GIGAMOLE** [comment]
What fo you mean? Can provide any example?

**Comment by xm-repo** [comment]
![2016-07-07 15 35 09](https://cloud.githubusercontent.com/assets/11179246/16653313/2540ee3c-4461-11e6-94c3-013d6b44923f.png)
something like this, or we can set background image for buttons maybe

**Comment by GIGAMOLE** [comment]
This enhancement is impossible cause of guidelines on NTB.
