### ISSUE TITLE
Different Fragment item each item view and image

### ISSUE THREAD

**Issue by triasbrata** [DevLight-Mobile-Agency/NavigationTabBar#38]
Thanks in advance for responding to bug I reported yesterday. and can you gives an example of the use of NTB with 4 Fragment different? because I have tried but to no avail, oh I want to create a navigation reference to NTB like Instagram. and whether the icon NTB may directly input in the form Bitmap without having at Convert to BitmapDrawable?

**Comment by GIGAMOLE** [comment]
Hello again. Thanks. You can just put a Drawable. If you want to create a NTB with 4 fragments use ViewPager, like in sample app.

**Comment by triasbrata** [comment]
i have doit 
and this my code https://gist.github.com/triasbrata/537a6309b929d25c57d0246127447c87
