### ISSUE TITLE
Cannot get badges to show

### ISSUE THREAD

**Issue by lappalj4** [DevLight-Mobile-Agency/NavigationTabBar#40]
Hi, 

Otherwise the NTB works like a charm, but I can't get the badges to show at all...

Here's my layout xml: 
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/main_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.gigamole.navigationtabbar.ntb.NavigationTabBar
        android:id="@+id/main_ntb"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_alignParentTop="true"
        app:ntb_animation_duration="200"
        app:ntb_active_color="#ffffff"
        app:ntb_inactive_color="@color/grey"
        app:ntb_badged="true"
        app:ntb_titled="false"
        app:ntb_scaled="false"
        app:ntb_tinted="true"
        app:ntb_badge_position="right"
        app:ntb_badge_gravity="bottom"
        app:ntb_badge_bg_color="@color/theme_red"
        app:ntb_badge_title_color="#ffffff"
        app:ntb_swiped="true"
        app:ntb_bg_color="@color/dark_grey"
        app:ntb_badge_size="10sp"
        app:ntb_title_size="10sp" />

    <io.altru.lack.components.NonSwipeableViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_below="@+id/main_ntb"
        android:layout_alignParentBottom="true"
        android:background="@color/lightgrey" />

</RelativeLayout>`

**Here's the code for setting up my NTB:** 

  navigationTabBar = (NavigationTabBar) findViewById(R.id.main_ntb);
  
  final ArrayList<NavigationTabBar.Model> models = new ArrayList<>();
  
  IconDrawable browse = new IconDrawable(this, TypiconsIcons.typcn_home_outline).sizeDp(40);
  
  IconDrawable create = new IconDrawable(this, TypiconsIcons.typcn_camera).sizeDp(40);
  
  IconDrawable lists = new IconDrawable(this, TypiconsIcons.typcn_pin).sizeDp(40);
  
  models.add(
                new NavigationTabBar.Model.Builder(browse, getResources().getColor(R.color.theme_accent))
                        .build()
        );
  
  models.add(
                new NavigationTabBar.Model.Builder(create, getResources().getColor(R.color.theme_accent))
                        .build()
        );
  
  models.add(
                new NavigationTabBar.Model.Builder(lists,     getResources().getColor(R.color.theme_accent))
                        .badgeTitle("Wee")
                        .build()
        );

   navigationTabBar.setModels(models);
   
   navigationTabBar.setViewPager(viewPager, 0);
   
   navigationTabBar.setIsBadged(true);

**And finally, here's the code where I try to show the badge (pretty much copied from the sample app):**

navigationTabBar.postDelayed(new Runnable() {
            @Override
            public void run() {
                final NavigationTabBar.Model model = navigationTabBar.getModels().get(0);
                Log.v(TAG, "Is badge showing before: " + model.isBadgeShowed());
                model.showBadge();
                Log.v(TAG, "Is badge showing after: " + model.isBadgeShowed());
            }
        }, 500);

In the last code snippet, the model.isBadgeShowed() returns false on both calls, both before and after calling model.showBadge()

Any help?

**Comment by GIGAMOLE** [comment]
Hello. Thanks for detailed issue. You cant show badge if tab have empty badge title. So, when you adf your models just set badge title to each of them and then you can show it.

**Comment by lappalj4** [comment]
Alright, thanks for the quick response and sorry for failing on inserting the code snippets :)

So in this particular snippet I realize I tried adding a badge to a model with an empty title, but before I tried adding it to the last one (which has a title) and it didn't work. Do I need to add a badge title to all of my models?

**Comment by lappalj4** [comment]
Here's an updated version of setting the models, which does not work either :(

models.add(
                new NavigationTabBar.Model.Builder(browse, getResources().getColor(R.color.theme_accent))
                        .badgeTitle("1")
                        .title("Wee")
                        .build()
        );
        models.add(
                new NavigationTabBar.Model.Builder(create, getResources().getColor(R.color.theme_accent))
                        .badgeTitle("2")
                        .title("Wee")
                        .build()
        );
        models.add(
                new NavigationTabBar.Model.Builder(lists, getResources().getColor(R.color.theme_accent))
                        .badgeTitle("3")
                        .title("Wee")
                        .build()
        );
        navigationTabBar.setModels(models);
        navigationTabBar.setViewPager(viewPager, 0);
        navigationTabBar.setIsBadged(true);
        navigationTabBar.setBadgeBgColor(Color.RED);
        navigationTabBar.setBadgeTitleColor(Color.WHITE);
        navigationTabBar.setBadgeSize(10);
        navigationTabBar.setTitleSize(10);

**Comment by GIGAMOLE** [comment]
The badges not showed?

**Comment by lappalj4** [comment]
Nope, they aren't showing. As a side note, with my current setup I didn't get the tab titles to show either.

**Comment by GIGAMOLE** [comment]
Do you call showBadge?

**Comment by GIGAMOLE** [comment]
If badge would have a not empty title there it eneabled to show.

**Comment by lappalj4** [comment]
I don't really understand, in my code all of the models have titles and badge titles, I am setting the navigation tab bar as titled and badged in the xml and I am setting it badged also in the activity code. No badges are showing and no titles are showing. I will have to switch to another library if this is not resolved soon.

**Comment by lappalj4** [comment]
I managed to get the badges and titles to display by wrapping my NavigationTabBar inside a FrameLayout. Perhaps this is a bug with android or the support libraries? In any case, please add this to the description so other people will know in the future. Thanks for your help!

**Comment by GIGAMOLE** [comment]
Thanks. Year there a bug of Android layout system.

**Comment by kaustubhbhagwat** [comment]
@lappalj4  cam you share your xml code i am facing the same issue but when i try to wrap NTB inside  a FrameLayout my app crashes

**Comment by lappalj4** [comment]
Here it is: 

`
<FrameLayout
            android:id="@+id/ntb_wrapper"
            android:layout_centerInParent="true"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:clipChildren="false"
            android:clipToPadding="false">

            <com.gigamole.navigationtabbar.ntb.NavigationTabBar
                android:id="@+id/main_ntb"
                android:layout_width="150dp"
                android:layout_height="50dp"
                android:layout_gravity="center"
                app:ntb_corners_radius="25dp"
                app:ntb_animation_duration="200"
                app:ntb_active_color="@color/theme_primary"
                app:ntb_inactive_color="@color/grey"
                app:ntb_badged="true"
                app:ntb_titled="false"
                app:ntb_scaled="false"
                app:ntb_tinted="true"
                app:ntb_badge_position="center"
                app:ntb_badge_gravity="bottom"
                app:ntb_badge_bg_color="@color/theme_accent"
                app:ntb_badge_title_color="#ffffff"
                app:ntb_swiped="true"
                app:ntb_bg_color="@color/transparent"
                app:ntb_badge_size="11dp"/>

        </FrameLayout>
`

And that is wrapped in a RelativeLayout that contains some other views I have in the toolbar, but they should be nothing relevant for this. Keep in mind that I have not updated the lib / changed the code since I last commented on this issue :)

**Comment by kaustubhbhagwat** [comment]
![screenshot_20170912-150720](https://user-images.githubusercontent.com/10204718/30319048-722f0b60-97cc-11e7-965e-024bbb86b36d.png)
Hello thanks a lot i can see the badges now but i see a black line on top of the NTB , and it goes away when i remove the FrameLayout.

**Comment by lappalj4** [comment]
@kaustubhbhagwat can't say why that would be happening, but I think you will be able to get rid of it by adjusting padding, margin and clip settings or just having a fixed height for both the framelayout and the NTB inside
