### ISSUE TITLE
Access modifiers

### ISSUE THREAD

**Issue by xm-repo** [DevLight-Mobile-Agency/NavigationTabBar#42]
Hello! Can you turn fields and methods in classes from private to protected, so we can extend your classes and override some features. Thx!

**Comment by GIGAMOLE** [comment]
Hello.
Thanks for repsonse.
Can you explain wich kind of changes do you want? Maybe you can come up with some pull request is the feature would be nice?

**Comment by GIGAMOLE** [comment]
Done already.
