### ISSUE TITLE
setIconSizeFraction()  float to double conversion error

### ISSUE THREAD

**Issue by samnockels** [DevLight-Mobile-Agency/NavigationTabBar#45]
When I try to set the following:   

`navigationTabBar.setIconSizeFraction(0.5);`

I get the error:

> Error:(115, 46) error: incompatible types: possible lossy conversion from double to float

Why is this? I have just updated my gradle to use version 1.2.4

**Comment by GIGAMOLE** [comment]
Hello. Thanks for question. As always 0.5 was float, but now you must concretize value with F flag such like this: 
navigationTabBar.setIconSizeFraction(0.5F);
