### ISSUE TITLE
Space between viewPager and Navigation Tab Bar when badged

### ISSUE THREAD

**Issue by darcheville06** [DevLight-Mobile-Agency/NavigationTabBar#46]
Hello,

there is a space between viewpager and navigation tab bar when badge mode is enabled, is it possible to remove this space please?

Thanks and Regards

**Comment by GIGAMOLE** [comment]
Hello.
Thanks for question.
As you can see this question link directly to android layouting system. If you use my sample, you can see the TopHorizontalNtbActivity where is some code:

navigationTabBar.post(new Runnable() {
            @Override
            public void run() {
                final View viewPager = findViewById(R.id.vp_horizontal_ntb);
                ((ViewGroup.MarginLayoutParams) viewPager.getLayoutParams()).topMargin =
                        (int) -navigationTabBar.getBadgeMargin();
                viewPager.requestLayout();
            }
        });

Which provide you feature where you can do what you want.

**Comment by darcheville06** [comment]
Thank you very much it works
