### ISSUE TITLE
Vertical NTB ,title dosen't show.

### ISSUE THREAD

**Issue by razvandalca** [DevLight-Mobile-Agency/NavigationTabBar#48]
I added a NTB and the title is enabled  but it doesn't show.
![image](https://cloud.githubusercontent.com/assets/13640843/17275792/b8757d08-571c-11e6-9fbe-6837142ab897.png)

When i put the NTB on a horizontal position all is good ,does NTB not support title in vertical position ? 
And another thing , i have many models ,how can i make the NTB scrollable so i can see all of them and just when i click a model to change the fragment from the view pager, is this supported ( i mean scrolling through the items of the NTB )?

Thank you :)

**Comment by GIGAMOLE** [comment]
Hello. Thanks for question. Vertical mode doesnt support titles. And scrolling mode not recommended by Google and NTB guidelines. Thanks.

**Comment by razvandalca** [comment]
Thank you 👍
