### ISSUE TITLE
setIconSizeFraction() missing in NavigationTabBar.java

### ISSUE THREAD

**Issue by searchy2** [DevLight-Mobile-Agency/NavigationTabBar#49]
navigationTabBar.setIconSizeFraction(0.5); in documentation does not work with compile:navigationtabbar1.2.3 
setIconSizeFraction() is either missing or the documentation is incorrect and it has been removed/replaced? 

The following picture displays the position from where the code is missing:
http://imgur.com/DZJZM4W
This is the code that is missing:
`    public float getIconSizeFraction() {
        return mIconSizeFraction;
    }
    // To reset scale fraction of icon to automatic just put in method AUTO_SCALE value
    public void setIconSizeFraction(final float iconSizeFraction) {
        mIconSizeFraction = iconSizeFraction;
        requestLayout();
    }`

Thank you for making such a great resource!

**Comment by GIGAMOLE** [comment]
Hello. Thanks for this issue. Id look it today and try to fix it.

**Comment by GIGAMOLE** [comment]
Hello. Thanks for this issue.
I forget to update NTB to 1.2.4 on Bintray. Wait for this.
