### ISSUE TITLE
get click on button when it is selected too

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [DevLight-Mobile-Agency/NavigationTabBar#53]
I am getting NVt button click Using  navigationTabBar.setOnTabBarSelectedIndexListener working good but when i going to click on pre-selected button it didnt show its postion how to get it I need to open Dialog on Click,  first time click it work but next time I have change selected Button and again come to same button to open dialog pls help

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue.
Because NTB doesnt trigger listeners when its the same position. Ok. Ill try to do this.

**Comment by GIGAMOLE** [comment]
Try new version 1.2.5. Thanks.

**Comment by sunil-singh-chaudhary** [comment]
I'll try tnx
