### ISSUE TITLE
problem in navbar

### ISSUE THREAD

**Issue by MarsXan** [DevLight-Mobile-Agency/NavigationTabBar#54]
Hi tanx for your good lib 
my english is not good sorry for that 
i have a problem i have add change possison in your code for example i want to start a progressbar 
when i am in tab 1 but it start in tab 2 and tab 1 what is the problem ?
if(position==0){
                    new JSONAsyncTask().execute("http://microblogging.wingnity.com/JSONParsingTutorial/jsonActors");
                    ArrayList<ListItem> listMockData = new ArrayList<ListItem>();
                    String[] images = getResources().getStringArray(R.array.images_array);
                    String[] headlines = getResources().getStringArray(R.array.headline_array);

                    for (int i = 0; i < images.length; i++) {
                        ListItem newsData = new ListItem();
                        newsData.setUrl(images[i]);
                        newsData.setHeadline(headlines[i]);
                        newsData.setReporterName("Pankaj Gupta");
                        newsData.setDate("May 26, 2013, 13:35");
                        listMockData.add(newsData);
                    }
                    ArrayList<ListItem> listData = listMockData;

                    final ListView listView = (ListView) findViewById(R.id.custom_list);
                    listView.setAdapter(new CustomListAdapter(Main.this, listData));
                    listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {

                        @Override
                        public void onItemClick(AdapterView<?> a, View v, int position, long id) {
                            ListItem newsData = (ListItem) listView.getItemAtPosition(position);
                            Toast.makeText(Main.this, "Selected :" + " " + newsData, Toast.LENGTH_LONG).show();
                        }
                    });
                }

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue.
Can you explain what exactly you want. I dont understand your question. And your pastecode doesnt provide any info. Wait for repsonse. Try to use latest update of NTB.
