### ISSUE TITLE
freeze page

### ISSUE THREAD

**Issue by BoneFletcher** [DevLight-Mobile-Agency/NavigationTabBar#55]
Hi all, thats my problem. I use in setOnTabBarSelectedIndexListener. fragment transaction and when open fragment with 1 view in layout, thats all ok, but when open layout with many view, selection page freeze from 0.4 to 2 second, it`s looking wery trouble, explain please what wrong. Thx to all.

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue.
This library does not affect the performance change tool, it only indicates the current index your screen. Try to look at your layouts and optimize them.
