### ISSUE TITLE
Setting default Icon 

### ISSUE THREAD

**Issue by abumoallim** [DevLight-Mobile-Agency/NavigationTabBar#56]
i want to set a coloured icon , but it fills the default color in the icon. i want to keep my icon as it is coloured without setting any colour through nt_inactive_color .

**Comment by GIGAMOLE** [comment]
Hello. Thanks for question.
Dow you want to keep original icon?

**Comment by abumoallim** [comment]
yes.

**Comment by abumoallim** [comment]
![2f9a6edf-9aff-40cc-96de-0c2d47f9f1d5](https://cloud.githubusercontent.com/assets/14852095/17766442/caeb0c52-6548-11e6-97e0-a2bd9785bec6.jpg)
see i want to keep the below image but it shows as shown above
![timecool](https://cloud.githubusercontent.com/assets/14852095/17766449/cd49ded8-6548-11e6-9edc-b830b6c384bf.png)

**Comment by GIGAMOLE** [comment]
Just set inactive_color to transparent color.

**Comment by abumoallim** [comment]
i did but it all goes blank. nothing display

**Comment by abumoallim** [comment]
Sir is it Possible Or not ? thank you for your time

**Comment by GIGAMOLE** [comment]
Ohhh. This is interesting. I'd look on it later. Work on another library.

**Comment by GIGAMOLE** [comment]
Solution will be on weekdays.

**Comment by abumoallim** [comment]
Ok sir thank You, will wait for the solution.

**Comment by dinhthaidaica** [comment]
do we have the final solution for this problem?

**Comment by GIGAMOLE** [comment]
Currenrly i cant answer. Try to find workaround alone.

**Comment by mitab86** [comment]
ok thanks for your fast feedback.if you can help with code in your free time..it would be well appreciated

**Comment by GIGAMOLE** [comment]
Just use app:ntb_tinted="false"
