### ISSUE TITLE
Selected index

### ISSUE THREAD

**Issue by juanlabrador** [DevLight-Mobile-Agency/NavigationTabBar#57]
How I can select index just to paint.

Because, the method setModelIndex call method onStartTabSelected and reset my fragment and don't want this.

I try to work with onBackPressed, when a fragment is removed and called who is top, then selected this tab. But how called onStartTabSelected this instance again. Thanks.

PD: I can't show badge too.

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue.
Try to set listener to null, then call setModelIndex(), and again set listener to your.
Can you explain about badge problem?

**Comment by juanlabrador** [comment]
Its a good idea. I try to work with a boolean, when onBackPressed is called, ignore the content inside onStartTabSelected. 

With Badge, I adjust my code:

`    <com.gigamole.navigationtabbar.ntb.NavigationTabBar
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:layout_alignParentBottom="true"
        android:layout_gravity="center"
        app:ntb_bg_color="@color/primary"
        app:ntb_active_color="#fff"
        app:ntb_scaled="false"
        app:ntb_inactive_color="#fff"
        app:ntb_animation_duration="0"
        app:ntb_badge_bg_color="@color/error"
        app:ntb_badge_gravity="top"
        app:ntb_badge_position="center"
        app:ntb_badge_title_color="#fff"
        app:ntb_badge_size="@dimen/normalText"
        app:ntb_badged="true"/>
`

`public void updateNotification(final int num) {
        final NavigationTabBar.Model model = mBottomNavigation.getModels().get(3);

        if (model == null) return;
        mBottomNavigation.postDelayed(new Runnable() {
            @Override
            public void run() {
                if (!model.isBadgeShowed()) {
                    model.setBadgeTitle(String.valueOf(num));
                    model.showBadge();
                } else model.updateBadgeTitle(String.valueOf(num));
            }
        }, 100);
    }`

First, not show nothing, I had try with some content static, but nothing, then I have this code, my position 3 is the tab with receive this notifications. I am doing something wrong? thank you.

**Comment by GIGAMOLE** [comment]
Try to set badge title from model builder and then just call showBadge() on model.

**Comment by juanlabrador** [comment]
I try to do this:

`final ArrayList<NavigationTabBar.Model> tabs = new ArrayList<>();
        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_home), 
                        getResources().getColor(R.color.accent)).build());
        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_search),
                        getResources().getColor(R.color.accent)).build());
        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_camera), 
                        getResources().getColor(R.color.accent)).build());
        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_notification),
                        getResources().getColor(R.color.accent))
                .badgeTitle("NTB").build());

        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_user), 
                        getResources().getColor(R.color.accent)).build());`

But not work

**Comment by juanlabrador** [comment]
The NTB is for to see if paint or show.

**Comment by GIGAMOLE** [comment]
Cause u  dont call setBadge() method pre build().

**Comment by juanlabrador** [comment]
I don't see where I add correctly

**Comment by GIGAMOLE** [comment]
Before u call build() method just call setBadgeTitle() and then build().

**Comment by juanlabrador** [comment]
Let me doing

**Comment by juanlabrador** [comment]
Well, I don't know if I had done, in the old coments.

```
tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_notification),
                        getResources().getColor(R.color.accent))
                .badgeTitle("NTB")
                .build());
```

**Comment by GIGAMOLE** [comment]
Yeah. Just like that.

**Comment by juanlabrador** [comment]
Nothing. I go to add my code:


       ```
 final ArrayList<NavigationTabBar.Model> tabs = new ArrayList<>();
        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_home), 
                        getResources().getColor(R.color.accent)).build());
        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_search),
                        getResources().getColor(R.color.accent))
                        .build());
        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_camera), 
                        getResources().getColor(R.color.accent)).build());
        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_notification),
                        getResources().getColor(R.color.accent))
                .badgeTitle("0")    ---->> HERE
                .build());

        tabs.add(new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.mipmap.ic_user), 
                        getResources().getColor(R.color.accent)).build());

        mBottomNavigation.setModels(tabs);
        mBottomNavigation.setOnTabBarSelectedIndexListener(new NavigationTabBar.OnTabBarSelectedIndexListener() {
            @Override
            public void onStartTabSelected(NavigationTabBar.Model model, int index) {
                switch (index) {
                    case 0:
                        i...
                        break;
                    case 1:
                      ....
                        break;
                    case 2:
                        ...
                        break;
                    case 3:
                        .....
                        model.hideBadge();
                        mBadgeCount = 0;
                        updateNotification(mBadgeCount);
                     
                        break;
                    case 4:
                       .....
                        break;
                }
            }

            @Override
            public void onEndTabSelected(NavigationTabBar.Model model, int index) {}
        });

        mBottomNavigation.setModelIndex(0);
```

**Comment by GIGAMOLE** [comment]
Do you call showBadge() method?

**Comment by juanlabrador** [comment]
Yeah, I created a method when I receive a count of notification
```

public void updateNotification(final int num) {
final NavigationTabBar.Model model = mBottomNavigation.getModels().get(3);

    if (model == null) return;
    mBottomNavigation.postDelayed(new Runnable() {
        @Override
        public void run() {
            if (!model.isBadgeShowed()) {
                model.setBadgeTitle(String.valueOf(num));
                model.showBadge();
            } else model.updateBadgeTitle(String.valueOf(num));
        }
    }, 100);
}`
```

**Comment by GIGAMOLE** [comment]
Try to wrap your NTB with FrameLayout or another ViewGroup.

**Comment by GIGAMOLE** [comment]
This is the bug of android where measering calculate incorrectlly cause of screen parent.

**Comment by juanlabrador** [comment]
How calculas publish a new version?

**Comment by GIGAMOLE** [comment]
What?

**Comment by juanlabrador** [comment]
update the library.

**Comment by GIGAMOLE** [comment]
Current version 1.2.5. Its latest.

**Comment by juanlabrador** [comment]
Yes, little bug, with LinearLayout show badge, but it add in spacing to top. With relativeLayout to asing NavigationBar to parentBotton, not show.

**Comment by GIGAMOLE** [comment]
Its the android bug. Currently i dont know how to fix this.
