### ISSUE TITLE
When using the setViewPager () method, while click the Tab, there will be some shake animation.

### ISSUE THREAD

**Issue by NicodeLee** [DevLight-Mobile-Agency/NavigationTabBar#58]
Thank for you job！ 
How to cancel it.

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue. Ill try to fix this.

**Comment by NicodeLee** [comment]
Here is the gif.
<img src="https://github.com/NicodeLee/ResourceCloud/blob/master/ntb.gif" alt="screenshot" title="screenshot" width="270" height="486" />

**Comment by GIGAMOLE** [comment]
What is offscreenPageLimit(). If it by default, set it to itemCount - 1.

**Comment by JasonQS** [comment]
it seems not work, and sample app has the same problem. is there a solution plz?
