### ISSUE TITLE
Visible badge on my NTB

### ISSUE THREAD

**Issue by tux-world** [DevLight-Mobile-Agency/NavigationTabBar#59]
i cant visible and showing badge on my NTB

    <com.gigamole.library.ntb.NavigationTabBar
        android:id="@+id/ntb_horizontal"
        android:layout_width="match_parent"
        android:layout_height="30dp"
        android:layout_gravity="center"
        android:background="@color/colorPrimary"
        app:ntb_active_color="#4527A0"
        app:ntb_badge_position="right"
        app:ntb_badge_gravity="top"
        app:ntb_badge_bg_color="#ffff0000"
        app:ntb_badge_title_color="#ffffffff"/>

code:

    private void initUI() {
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_star),
                        Color.parseColor(colors[2]))
                        .build()
        );
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_blog),
                        Color.parseColor(colors[3]))
                        .badgeTitle("777")
                        .build()
        );
        navigationTabBar.setModels(models);
        navigationTabBar.setViewPager(viewPager, 0);
    }

Screen shot:

http://uupload.ir/files/1qpg_photo_2016-08-26_14-23-40.jpg

**Comment by GIGAMOLE** [comment]
Hello. Thanks for question. Do you set ntb_badged="true". Do you call showBadge() method on yor models? If not, try to done this.

**Comment by tux-world** [comment]
@GIGAMOLE Thanks. how can i call showBadge() i get error on this code sir

    private void initUI() {
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_star),
                        Color.parseColor(colors[2]))
                        .build()
        );
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_blog),
                        Color.parseColor(colors[3]))
                        .badgeTitle("777")
                        .build()
        );
        models.showBadge();
    }

**Comment by GIGAMOLE** [comment]
This is incorrect. You must do like this: models.get(1).showBadge();
