### ISSUE TITLE
change NTB badge position with padding or margin

### ISSUE THREAD

**Issue by tux-world** [DevLight-Mobile-Agency/NavigationTabBar#60]
Hi, how can i set ```padding``` and ```margin``` for badge and change the position like with ``` ICON (1)``` right of icon or left or that, Thanks

**Comment by GIGAMOLE** [comment]
You cant do this. NTB show badges only in predefined places.

**Comment by tux-world** [comment]
could you change position of badge after payment support cost?

**Comment by GIGAMOLE** [comment]
Currently i cant do this. A lot of work.
