### ISSUE TITLE
Fab Button layout_marginBottom="76dp" is not 16dp above from NavigationTabBar.

### ISSUE THREAD

**Issue by dyguests** [DevLight-Mobile-Agency/NavigationTabBar#65]
Android Studio 2.1.3.
gradle:2.1.3
compileSdkVersion 24
buildToolsVersion "24.0.0"
minSdkVersion  14
targetSdkVersion 24

```
compile 'com.android.support:design:24.2.0'
compile 'com.android.support:appcompat-v7:24.2.0'
compile 'com.github.devlight.navigationtabbar:navigationtabbar:1.2.5'
```

It's not work good on SnakeBar showed.

By use layout_marginBottom="76dp",the Fab Button is 16dp above from NavigationTabBar.
But when SnakeBar showed ,it's 76dp+snakeBar's heigt above from NavigationTabBar.

![screenshot_2016-09-06-15-35-33_com lxt msgr](https://cloud.githubusercontent.com/assets/7933189/18265320/bd683a9c-7447-11e6-8363-f811cbd83813.png)
![screenshot_2016-09-06-15-35-34_com lxt msgr](https://cloud.githubusercontent.com/assets/7933189/18265321/be5e2e0c-7447-11e6-8ce1-2453244cdd36.png)

**Comment by GIGAMOLE** [comment]
Thanks. Try to fix this soon.

**Comment by mitab86** [comment]
hello can you share your code how to get this?? i really liked to use but dont know how to use

**Comment by GIGAMOLE** [comment]
Try to decompile my sources and change some logic in classes. Thanks. Currently i cant do this.

**Comment by mitab86** [comment]
i have error in navigationTabBar.setViewPager(viewPager, 2);
what i have to do in viewPager?

**Comment by GIGAMOLE** [comment]
What error? What you mean?

**Comment by mitab86** [comment]
i have cannot resolve symbol viewpager in code..
i used this sample code in xml
  <com.gigamole.navigationtabbar.ntb.NavigationTabBar
        android:id="@+id/ntb"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        app:ntb_animation_duration="400"
        app:ntb_preview_colors="@array/array_dot_active"
        app:ntb_corners_radius="10dp"
        app:ntb_active_color="#fff"
        app:ntb_inactive_color="#000"
        app:ntb_badged="true"
        app:ntb_titled="true"
        app:ntb_scaled="true"
        app:ntb_tinted="true"
        app:ntb_title_mode="all"
        app:ntb_badge_position="right"
        app:ntb_badge_gravity="top"
        app:ntb_badge_bg_color="#ffff0000"
        app:ntb_badge_title_color="#ffffffff"
        app:ntb_typeface="fonts/custom_typeface.ttf"
        app:ntb_badge_use_typeface="true"
        app:ntb_swiped="true"
        app:ntb_bg_color="#000"
        app:ntb_icon_size_fraction="0.5"
        app:ntb_badge_size="10sp"
        app:ntb_title_size="10sp"/>

**Comment by mitab86** [comment]
i just copied and pasted your code and in viewPager i got cannot resolve symbol

**Comment by GIGAMOLE** [comment]
Do you import support library?

**Comment by mitab86** [comment]
yes i have imported

**Comment by GIGAMOLE** [comment]
Its interesting. Try to use correct imports.

**Comment by mitab86** [comment]
i have imported the support library and used the same code that you have provided.. what i have to do in viewpager??do i have to do something in xml or code extra something?

**Comment by mitab86** [comment]
i have used inside fragment

**Comment by mitab86** [comment]
in fragment i have done


@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view=inflater.inflate(R.layout.fragment_main, container, false);
        // Inflate the layout for this fragment
        final NavigationTabBar navigationTabBar = (NavigationTabBar) view.findViewById(R.id.ntb);
        final ArrayList<NavigationTabBar.Model> models = new ArrayList<>();
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_menu_camera),
                        Color.parseColor("#636161")
                ).title("Heart")
                        .badgeTitle("NTB")
                        .build()
        );
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_menu_gallery),
                        Color.parseColor("#636161")
                ).title("Cup")
                        .badgeTitle("with")
                        .build()
        );
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_menu_manage),
                        Color.parseColor("#636161")
                ).title("Diploma")
                        .badgeTitle("state")
                        .build()
        );
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_menu_send),
                        Color.parseColor("#636161")
                ).title("Flag")
                        .badgeTitle("icon")
                        .build()
        );
        models.add(
                new NavigationTabBar.Model.Builder(
                        getResources().getDrawable(R.drawable.ic_menu_slideshow),
                        Color.parseColor("#636161")
                ).title("Medal")
                        .badgeTitle("777")
                        .build()
        );
        navigationTabBar.setModels(models);
        navigationTabBar.setViewPager(viewPager, 2);

        navigationTabBar.setTitleMode(NavigationTabBar.TitleMode.ACTIVE);
        navigationTabBar.setBadgeGravity(NavigationTabBar.BadgeGravity.BOTTOM);
        navigationTabBar.setBadgePosition(NavigationTabBar.BadgePosition.CENTER);
        navigationTabBar.setTypeface("fonts/custom_font.ttf");
        navigationTabBar.setIsBadged(true);
        navigationTabBar.setIsTitled(true);
        navigationTabBar.setIsTinted(true);
        navigationTabBar.setIsBadgeUseTypeface(true);
        navigationTabBar.setBadgeBgColor(Color.RED);
        navigationTabBar.setBadgeTitleColor(Color.WHITE);
        navigationTabBar.setIsSwiped(true);
        navigationTabBar.setBgColor(Color.BLACK);
        navigationTabBar.setBadgeSize(10);
        navigationTabBar.setTitleSize(10);
        navigationTabBar.setIconSizeFraction((float) 0.5);
        return view;
    }



and in xml i have done
<com.gigamole.navigationtabbar.ntb.NavigationTabBar
        android:id="@+id/ntb"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        app:ntb_animation_duration="400"
        app:ntb_preview_colors="@array/array_dot_active"
        app:ntb_corners_radius="10dp"
        app:ntb_active_color="#fff"
        app:ntb_inactive_color="#000"
        app:ntb_badged="true"
        app:ntb_titled="true"
        app:ntb_scaled="true"
        app:ntb_tinted="true"
        app:ntb_title_mode="all"
        app:ntb_badge_position="right"
        app:ntb_badge_gravity="top"
        app:ntb_badge_bg_color="#ffff0000"
        app:ntb_badge_title_color="#ffffffff"
        app:ntb_typeface="fonts/custom_typeface.ttf"
        app:ntb_badge_use_typeface="true"
        app:ntb_swiped="true"
        app:ntb_bg_color="#000"
        app:ntb_icon_size_fraction="0.5"
        app:ntb_badge_size="10sp"
        app:ntb_title_size="10sp"/>
