### ISSUE TITLE
is there a way to disable icon scaling ?

### ISSUE THREAD

**Issue by mohamedkomalo** [DevLight-Mobile-Agency/NavigationTabBar#66]
use the icon with its own size without scaling. is there a way to do this ?

**Comment by GIGAMOLE** [comment]
Hello. Thanks for question.
Just set attr ntb_scaled="false".

**Comment by mohamedkomalo** [comment]
@GIGAMOLE thanks for your help, however using "ntb_scaled" only prevent title from being scaled, but icon still being scaled.

It seems that for icon scaling is done either scaled attr is set or not, But for text size, scaling is done only if scaled is true.

https://github.com/DevLight-Mobile-Agency/NavigationTabBar/blob/master/navigationtabbar/src/main/java/com/gigamole/navigationtabbar/ntb/NavigationTabBar.java#L1479

**Comment by GIGAMOLE** [comment]
Ohhh. Thanks for the correct bug fix.
