### ISSUE TITLE
Add Fragment to Viewpager

### ISSUE THREAD

**Issue by huykhoi1993** [DevLight-Mobile-Agency/NavigationTabBar#69]
Hi pro!
I want add many fragment to Viewpager. But I can't add fragment to viewpage. Can you write example about it?
Thanks U very much. :D

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue. 
Just set FragmentPagerAdapter except of PagerAdapter.

**Comment by huykhoi1993** [comment]
Yes sir.
Tks you very much ^^
