### ISSUE TITLE
Background won't changed

### ISSUE THREAD

**Issue by Dule95D** [DevLight-Mobile-Agency/NavigationTabBar#70]
I have tried to change background, but haven't succeeded in that. Here is what i have done so far:

`<com.gigamole.navigationtabbar.ntb.NavigationTabBar
        android:id="@+id/bottom_tab"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:background="@color/colorPrimaryDark" // This is not working
        app:ntb_badge_gravity="top"
        app:ntb_badge_position="right"
        app:ntb_badged="true"
        app:ntb_scaled="true"
        app:ntb_tinted="true"
        app:ntb_title_mode="all"
        app:ntb_titled="true"
        app:ntb_swiped="true"/>`

**Comment by GIGAMOLE** [comment]
Hello. 
Thanks for an issue. 
Just use attr ntb_background.

**Comment by Dule95D** [comment]
Hello. 
Thank you for answering me this fast, but it seems i can't use that attribute. I can't see it.

**Comment by GIGAMOLE** [comment]
Sorry.. Use ntb_bg_color.
