### ISSUE TITLE
How to use TabBar vertical  Icon+Text

### ISSUE THREAD

**Issue by tor9771** [DevLight-Mobile-Agency/NavigationTabBar#71]
I Can't Set Icon and Text to show Vertical,How to set property to use TabBar vertical  Icon+Text    Thank.

<img width="95" alt="screen shot 2559-10-20 at 11 16 12 am" src="https://cloud.githubusercontent.com/assets/1038173/19546086/a704ec8c-96b6-11e6-9960-fb29de2dbeed.png">

**Comment by GIGAMOLE** [comment]
Hello. Currently you cant do this.

**Comment by tor9771** [comment]
current show icon only whith vertivcal not show text  , if horizontal this show icon+text
