### ISSUE TITLE
when using it with a viewpager+fragment,the index is a mess

### ISSUE THREAD

**Issue by guyuepeng** [DevLight-Mobile-Agency/NavigationTabBar#72]
#### first of all,the lib is excellent!

but i found if i use it with a viewpager and fragments,the index is a mess.
u can try:
when i choose the first tab item,the log show me that i click the first and the second item at once.
and the index of the tabbar not the same as the viewpager's.

**Comment by GIGAMOLE** [comment]
Hello. Thanks for the issue. That's the problem of the ViewPager, so you can ignore this.

**Comment by cyan333** [comment]
@guyuepeng The index is correct. When you load a page with Viewpager, it automatically predicts and creates the next tab. For example, when you click the first tab, it will also initiate the second tab at the same time. This is why you see two Log (which shows the positions) at the same time.

**Comment by waleedmakarem** [comment]
I am having this issue. how to resolve.  When index change, i have to populate table data, so takes time. So, how to know the accurate tab index. 
Thanks for support
