### ISSUE TITLE
When swiping through pages, page deceleration

### ISSUE THREAD

**Issue by eerikk** [DevLight-Mobile-Agency/NavigationTabBar#73]
When i'm swiping through pages with left/right swipe, there is a slight deceleration when pages change. I checked your sample app and the same thing happens there. I guess it's because of the default 'animation duration' variable. Is there an option to totally remove the 'animation duration' so it would be possible to smoothly swipe through pages ?

**Comment by GIGAMOLE** [comment]
Hello.
Sorry for the late answer.
You can set animation duration with:
app:ntb_animation_duration="0" and create own ViewPager with disabled swipe.
