### ISSUE TITLE
Failed to get resource: GET. [HTTP HTTP/1.1 401 Repo not found or no access token provided:]

### ISSUE THREAD

**Issue by atulgoswami21** [DevLight-Mobile-Agency/NavigationTabBar#75]
Failed to get resource: GET. [HTTP HTTP/1.1 401 Repo not found or no access token provided: https://jitpack.io/com/github/devlight/navigationtabbar/navigationtabbar/maven-metadata.xml]

**Comment by GIGAMOLE** [comment]
Hello. Thanks for an issue.
Currently there no problem with this library. I have already compiled it and there was nothing problems.
