### ISSUE TITLE
Unable to put the NTB at bottom of screen

### ISSUE THREAD

**Issue by kumarkeviv** [DevLight-Mobile-Agency/NavigationTabBar#79]
Hi Team

I am trying to place the Navigation Tab Bar at the bottom of the activity but unable to make do so. There is always a space in between the bottom and the Tab Bar.

Please help I can't understand what is the issue with this. Here is the layout of the activity.

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">

    <android.support.v4.view.ViewPager
        android:id="@+id/vp_horizontal_ntb"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

    <devlight.io.library.ntb.NavigationTabBar
        android:id="@+id/ntb_horizontal"
        app:ntb_badge_gravity="top"
        app:ntb_badge_position="right"
        app:ntb_badged="true"
        app:ntb_scaled="true"
        app:ntb_swiped="true"
        app:ntb_tinted="true"
        android:layout_width="match_parent"
        android:layout_height="60dp" />

</LinearLayout>`
```

Also attaching the snapshot, to better understand the issue. Thank you so much in advance.
![screenshot_2016-12-21-00-06-22](https://cloud.githubusercontent.com/assets/17118240/21363146/62b30ae2-c711-11e6-917f-458a5d9b7eda.png)

**Comment by egenvall** [comment]
Experiencing the same issue.

    <FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.view.ViewPager
        android:id="@+id/view_pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="64dp" />

    <devlight.io.library.ntb.NavigationTabBar
    android:layout_gravity="bottom"
    android:id="@+id/ntb"
    android:layout_width="match_parent"
    android:layout_height="64dp"
    ...

**Comment by egenvall** [comment]
@kumarkeviv After taking on this problem again, the "issue" is using

        app:ntb_badge_gravity="top"
        app:ntb_badge_position="right"
        app:ntb_badged="true"

Will allocate space as if you had a badge, which makes sense. 
Remove these and the whitespace at the top/bottom should be removed.

**Comment by kumarkeviv** [comment]
@egenvall  Thanks for the help.
