### ISSUE TITLE
onConfigurationChanged ui bug

### ISSUE THREAD

**Issue by Neovyse** [DevLight-Mobile-Agency/NavigationTabBar#8]
hi, thanks for this lib, i see a bug when the navigationtabbar is in the bottom of the activity. When the activity is not recreated. In orientation changed the item in navigation bar is not correctly selected, the color not appear correctly over the item and sometimes the item selected is landscape is different that the item selected in portrait.

**Comment by GIGAMOLE** [comment]
Hi. Thanks. I have been tested in different orientations and there is no bugs. Can u tell me in what phone you have this bug. I'll tried to fix it and push new release. Thanks.

**Comment by Neovyse** [comment]
Hi, i have an HTC one m8 on android 6.0.
for testing you need to add in manifest android:configChanges="orientation|keyboardHidden|screenSize" on your activity who have navigationTabBar to be sure that the activity is not recreated. 

Screenshot portrait : http://www.hostingpics.net/viewer.php?id=652489Screenshot20160417125051copy.png
Screenshot landscape : http://www.hostingpics.net/viewer.php?id=634360Screenshot20160417125102copy.png

**Comment by GIGAMOLE** [comment]
Yeap. I`m found this but in all phones > 13 whitch this configChanges prop. And i`m fix it. Check new 1.1.4 version. Thanks.
