### ISSUE TITLE
Disable icon scale animation

### ISSUE THREAD

**Issue by Witype** [DevLight-Mobile-Agency/NavigationTabBar#9]
how can I clear icon animation(scale),by the way,how to use custom animation instead default,just like the last image in readMe,and,there is a white space on badge,it can be dismiss when badge dismiss?
![image](https://cloud.githubusercontent.com/assets/6899329/14643771/3e362546-0682-11e6-88bc-e79252faf5bc.png)

**Comment by GIGAMOLE** [comment]
Thanks for issue. White color is the background of your parent view and the color of badge also white, so there is the effect. Of course you can. Just remove the code in HorizontalNtbActivity where Iam change the height of NTB.

**Comment by GIGAMOLE** [comment]
Ok. I`ll add this feature for you. Thanks.

**Comment by Witype** [comment]
Thanks

**Comment by GIGAMOLE** [comment]
Update 1.1.5 on release. Thanks,
